#!/bin/bash

# Apps
#spotify &
#vesktop &
#thunderbird &
#obsidian &

# Terminal Apps
#kitty --class btop btop &
#kitty --class nvtop nvtop &

# Cursors
hyprctl setcursor catppuccin-macchiato-dark-cursors 32 &
