################
### MONITORS ###
################


monitor = eDP-1, 1920x1080@60, 0x0, 1


###################
### MY PROGRAMS ###
###################
$themes = bash ~/Documents/themes/theme-switcher.sh
$terminal = kitty
$fileManager = thunar
$browser = firefox
$menu = rofi -show drun #wofi -show drun
$powermenu = zsh ~/.config/rofi/powermenu.sh
#$powermenu = rofi -show power-menu -modi power-menu:rofi-power-menu
$screenshot = hyprshot -m output -m active --clipboard-only
$hyprlock = hyprlock
$killpanel = killall waybar
$startpanel = waybar

##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrulev2 = suppressevent maximize, class:.*
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
