source = ~/.conig/hypr/autostart.cofig
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/generals.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/themes/lavender/decorations.conf
